const RegionalIndicators = {
    A: '🇦',
    B: '🇧',
    C: '🇨',
    D: '🇩',
    E: '🇪',
    F: '🇫',
    G: '🇬',
    H: '🇭',
    I: '🇮',
    J: '🇯',
    K: '🇰',
    L: '🇱',
    M: '🇲',
    N: '🇳',
    O: '🇴',
    P: '🇵',
    Q: '🇶',
    R: '🇷',
    S: '🇸',
    T: '🇹',
    U: '🇺',
    V: '🇻',
    W: '🇼',
    X: '🇽',
    Y: '🇾',
    Z: '🇿'
} as Record<string,string>;

export const CountryCodes = {
    'AT': 'Austria',
    'AU': 'Australia',
    'AX': 'Åland',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BR': 'Brazil',
    'CA': 'Canada',
    'CH': 'Switzerland',
    'CN': 'China',
    'CO': 'Colombia',
    'CW': 'Curaçao',
    'CY': 'Cyprus',
    'DE': 'Germany',
    'DK': 'Denmark',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'ET': 'Ethiopia',
    'ES': 'Spain',
    'FI': 'Finland',
    'FM': 'Micronesia',
    'FR': 'France',
    'GB': 'United Kingdom',
    'GM': 'Gambia',
    'GR': 'Greece',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IT': 'Italy',
    'IQ': 'Iraq',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'KN': 'Saint Kitts and Nevis',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'LA': 'Laos',
    'LS': 'Lesotho',
    'LY': 'Libya',
    'MD': 'Moldova',
    'MF': 'Saint Martin',
    'MK': 'North Macedonia',
    'MN': 'Mongolia',
    'MO': 'Macau',
    'MQ': 'Martinique',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'PF': 'French Polynesia',
    'PL': 'Poland',
    'PR': 'Puerto Rico',
    'PS': 'Palestine',
    'PT': 'Portugal',
    'PW': 'Palau',
    'RE': 'Réunion',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SY': 'Syria',
    'TC': 'Turks and Caicos Islands',
    'TH': 'Thailand',
    'TL': 'East Timor',
    'TR': 'Turkey',
    'TT': 'Trinidad and Tobago',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'US': 'United States',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VI': 'U.S. Virgin Islands',
    'WF': 'Wallis and Futuna',
    'WI': 'Worldwide',
    'YT': 'Mayotte',
    'ZA': 'South Africa',

} as Record<string,string>;

export const ReverseCountryCodes = Object.fromEntries(Object.entries(CountryCodes).map(([a,b]) => [b,a]));

export function getCountryFlag(country: string) {
    if (country == 'UK') return '🇬🇧';
    if (country == 'WI') return '🌐';
    return country.split('').map(a => RegionalIndicators[a.toUpperCase()] || a).join('');
}
