name: BuildWeb
on: 
 workflow_dispatch:
 push:
 schedule:
    - cron: '59 18 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-web:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - uses: oven-sh/setup-bun@v2
    - uses: mlugg/setup-zig@v2
    - run: zig build-lib watchos.cpp -dynamic -lc -lc++
    - run: zig build-lib carrierdedupe.cpp -dynamic -lc -lc++
    - run: bash prepare.sh
    - run: bun install
    - run: bun run ./carrierbundles.ts
    - run: bun run ./build.ts
    - run: bash cleanup.sh
    - uses: actions/upload-pages-artifact@v3
      with:
        path: html
    - name: Deploy to GitHub Pages
      id: deployment 
      uses: actions/deploy-pages@v4

    
    